"""Update all datetime columns to be timezone-aware

Revision ID: 4110d6b038ab
Revises: 5aac086484ba
Create Date: 2025-10-20 21:58:09.857797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4110d6b038ab'
down_revision: Union[str, None] = '5aac086484ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing indexes first
    op.drop_index('idx_spike_schedule_fields_original', table_name='spike_schedule_fields')
    op.drop_index('idx_spike_schedule_fields_schedule', table_name='spike_schedule_fields')
    op.drop_index('idx_spike_schedules_collection', table_name='spike_schedules')
    op.drop_index('idx_spike_schedules_datetime', table_name='spike_schedules')
    
    # Note: SQLite doesn't support altering column types to add timezone constraints
    # The timezone-aware datetime will be handled at the application level
    # Existing data will be treated as UTC when loaded with timezone-aware models
    
    # Recreate indexes for performance
    op.create_index('idx_spike_schedules_datetime', 'spike_schedules', ['start_datetime', 'end_datetime'], unique=False)
    op.create_index('idx_spike_schedules_collection', 'spike_schedules', ['collection_id'], unique=False)
    op.create_index('idx_spike_schedule_fields_schedule', 'spike_schedule_fields', ['spike_schedule_id'], unique=False)
    op.create_index('idx_spike_schedule_fields_original', 'spike_schedule_fields', ['original_field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop timezone-aware indexes
    op.drop_index('idx_spike_schedules_datetime', table_name='spike_schedules')
    op.drop_index('idx_spike_schedules_collection', table_name='spike_schedules')
    op.drop_index('idx_spike_schedule_fields_schedule', table_name='spike_schedule_fields')
    op.drop_index('idx_spike_schedule_fields_original', table_name='spike_schedule_fields')
    
    # Recreate original indexes
    op.create_index('idx_spike_schedules_datetime', 'spike_schedules', ['start_datetime', 'end_datetime'], unique=False)
    op.create_index('idx_spike_schedules_collection', 'spike_schedules', ['collection_id'], unique=False)
    op.create_index('idx_spike_schedule_fields_schedule', 'spike_schedule_fields', ['spike_schedule_id'], unique=False)
    op.create_index('idx_spike_schedule_fields_original', 'spike_schedule_fields', ['original_field_id'], unique=False)
    # ### end Alembic commands ###
